### ISSUE TITLE
Can you do something about conflict with pulseeffects?

### ISSUE THREAD

**Issue by GoodGuyNick** [yktoo/indicator-sound-switcher#66]
Here is the issue https://github.com/wwmm/pulseeffects/issues/371.
`It seems to me that this indicator you are using moves all audio applications to the device you selected. More or less the same that Enable All Applications does. There will be definitely a conflict.`

**Comment by yktoo** [comment]
I'm not sure what is expected to be done here.

Yes, the SSI moves all active inputs to the selected sink, this is by design and is also consistent with how Gnome Sound Panel handles default device switching. If it isn't what you want then probably this indicator is not for you and you need to choose another tool.

**Comment by yktoo** [comment]
I've checked that out and it seems the indicator does work correctly with `pulseeffects`. Please reopen if you still experience this.
